/* Letterbooxd Arcade — dependency-free game controllers. */
const ARCADE_GAMES = [
  {id:'bookworm',name:'Bookworm',desc:'Gather loose pages without tangling the longest reader in the stacks.',metric:'pages',icon:'<path d="M12 54c8-18 17-25 30-20s16-10 26-17"/><circle cx="12" cy="54" r="7"/><circle cx="42" cy="34" r="7"/><path d="M4 11h22v28H4zM26 11h22v28H26"/>'},
  {id:'shelf-breaker',name:'Shelf Breaker',desc:'Return every stubborn volume with a bouncing library stamp.',metric:'points',icon:'<path d="M5 14h65M8 15v13h9V15m4 0v13h14V15m5 0v13h8V15m5 0v13h15V15M5 30h65M20 55h40"/><circle cx="39" cy="44" r="5"/>'},
  {id:'cover-match',name:'Cover Match',desc:'Pair eight covers from the Letterbooxd catalogue before time runs on.',metric:'moves',icon:'<rect x="7" y="8" width="25" height="36"/><rect x="42" y="22" width="25" height="36"/><path d="M14 16h11M49 30h11"/>'},
  {id:'guess-the-cover',name:'Guess the Cover',desc:'Recognise a catalogue cover as it slowly emerges from the blur.',metric:'points',icon:'<rect x="12" y="7" width="42" height="56"/><path d="M19 15h9v9h-9zm18 0h9v9h-9zM19 33h9v9h-9zm18 0h9v9h-9z"/>'},
  {id:'first-edition',name:'First Edition',desc:'Choose which of two books reached readers first. Build a streak.',metric:'streak',icon:'<path d="M7 12h28v45H7zM40 5h28v45H40zM14 21h14M47 14h14"/>'}
];
let arcadeCleanup = [];
let arcadeCatalogCache = [];
const arcadeRoot = () => document.getElementById('arcade-root');
const onCleanup = fn => arcadeCleanup.push(fn);
function cleanupArcade(){ arcadeCleanup.splice(0).forEach(fn=>{try{fn()}catch(e){}}); }
function arcadeBest(id){ try{return JSON.parse(localStorage.getItem(`lbx_arcade_${id}`)||'null')}catch(e){return null} }
function saveArcadeBest(id,value,lower=false){const old=arcadeBest(id);if(old==null||(lower?value<old:value>old)){localStorage.setItem(`lbx_arcade_${id}`,JSON.stringify(value));if(state.user&&sb)sb.from('arcade_scores').upsert({user_id:state.user.id,game:id,score:value,updated_at:new Date().toISOString()},{onConflict:'user_id,game'}).then(()=>{});return true}return false}
async function syncArcadeScores(){if(!state.user||!sb)return;try{const {data}=await sb.from('arcade_scores').select('game,score').eq('user_id',state.user.id);(data||[]).forEach(r=>{const lower=r.game==='cover-match',local=arcadeBest(r.game);if(local==null||(lower?r.score<local:r.score>local))localStorage.setItem(`lbx_arcade_${r.game}`,JSON.stringify(r.score))})}catch(e){}}
function shuffle(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function arcadeIcon(game){return `<div class="arcade-icon"><svg viewBox="0 0 76 70" aria-hidden="true">${game.icon}</svg></div>`}
function arcadePreview(id){
  if(id==='bookworm')return '<div class="card-preview preview-worm"><i></i><i></i><i></i><span></span><b>PAGE +1</b></div>';
  if(id==='shelf-breaker')return '<div class="card-preview preview-shelf"><span></span><span></span><span></span><span></span><i></i><b></b></div>';
  if(id==='cover-match')return '<div class="card-preview preview-match"><i></i><i></i><i></i></div>';
  if(id==='guess-the-cover')return '<div class="card-preview preview-guess"><i></i><span>?</span><b>FOCUS 20%</b></div>';
  return '<div class="card-preview preview-edition"><i></i><strong>VS</strong><i></i><b>19??</b></div>';
}
function openArcadeGame(id){navigate('arcade',{game:id});}
function loadArcadePage(game){cleanupArcade();if(game&&ARCADE_GAMES.some(g=>g.id===game))renderArcadeGame(game);else renderArcadeOverview()}
async function renderArcadeOverview(){await syncArcadeScores();if(state.currentPage!=='arcade')return;arcadeRoot().innerHTML=`<header class="arcade-mast"><div class="arcade-mast-copy"><span class="arcade-kicker">Letterbooxd presents / after hours</span><h1><span>Letterbooxd</span>Arcade</h1><p>Five small games for people who should probably be reading.</p><button class="arcade-play arcade-random">Random game →</button></div><div class="arcade-mast-register" aria-hidden="true"><span>PLAYER 01</span><span>REF. LBX/05</span><b>✦</b><i>INSERT<br>BOOKMARK</i><em>05<br>GAMES</em></div></header><div class="arcade-index"><span>SELECT A VOLUME</span><span>HIGH SCORES SAVED LOCALLY</span><span>01—05</span></div><section class="arcade-grid">${ARCADE_GAMES.map((g,i)=>`<article class="arcade-card" tabindex="0" role="link" data-card-game="${g.id}" aria-label="Play ${g.name}"><div class="arcade-card-head"><span class="arcade-label">0${i+1}</span><span>${g.metric}</span></div><div class="arcade-card-visual">${arcadePreview(g.id)}${arcadeIcon(g)}</div><div class="arcade-card-copy"><span class="arcade-category">${i<2?'Reflex / catalogue':'Catalogue / puzzle'}</span><h2>${g.name}</h2><p>${g.desc}</p></div><div class="arcade-card-foot"><span class="arcade-best"><b>${arcadeBest(g.id)!=null?arcadeBest(g.id):'—'}</b> personal best</span><button class="arcade-play" data-game="${g.id}">Play →</button></div></article>`).join('')}</section>`;const open=id=>openArcadeGame(id);arcadeRoot().querySelector('.arcade-random').onclick=()=>open(shuffle([...ARCADE_GAMES])[0].id);arcadeRoot().querySelectorAll('[data-card-game]').forEach(card=>{card.onclick=e=>{if(!e.target.closest('button'))open(card.dataset.cardGame)};card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(card.dataset.cardGame)}}});arcadeRoot().querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>open(b.dataset.game))}
function gameShell(game,stats,stage,note=''){const gameNo=String(ARCADE_GAMES.findIndex(g=>g.id===game.id)+1).padStart(2,'0');arcadeRoot().innerHTML=`<div class="game-topbar"><button class="game-back">← Arcade</button><span>${gameNo} / ${game.name}</span></div><header class="game-heading"><div><span class="arcade-label">Player 01 / ready</span><h1>${game.name}</h1></div><p>${game.desc}</p></header><section class="game-frame"><div class="game-stats">${stats.map(([id,label,val])=>`<div class="game-stat"><span>${label}</span><strong id="${id}">${val}</strong></div>`).join('')}</div><div class="game-stage">${stage}</div><footer class="game-panel"><div class="game-actions" id="game-actions"></div>${note?`<p class="game-note"><span>How to play</span>${note}</p>`:''}</footer></section>`;arcadeRoot().querySelector('.game-back').onclick=()=>navigate('arcade')}
function renderArcadeGame(id){const game=ARCADE_GAMES.find(g=>g.id===id);if(id==='bookworm')bookworm(game);if(id==='shelf-breaker')shelfBreaker(game);if(id==='cover-match')coverMatch(game);if(id==='guess-the-cover')guessCover(game);if(id==='first-edition')firstEdition(game)}

async function getArcadeCatalog(years=false){
  let books=[...(state.popularBooks||[]),...(state.classicsBooks||[]),...(state.fictionBooks||[]),...Object.values(state.readBooks||{}),...Object.values(state.wishlist||{})];
  books=[...new Map(books.filter(b=>b&&b.title&&b.coverUrl).map(b=>[normalizeText(b.title),b])).values()];
  if(books.length<16){try{books.push(...await fetchOLTrending(50))}catch(e){}}
  books=[...new Map(books.filter(b=>b&&b.title&&b.coverUrl&&(!years||(+b.year>1000&&+b.year<=new Date().getFullYear()))).map(b=>[normalizeText(b.title),b])).values()];
  arcadeCatalogCache=books;return books;
}
function coverMarkup(b,cls=''){const src=coverUrl(b.coverUrl,'L');return `<img class="${cls}" src="${escHtml(src)}" alt="Cover of ${escHtml(b.title)}" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><span class="cover-placeholder" style="display:none">${escHtml(b.title)}</span>`}

function bookworm(game){
  gameShell(game,[['worm-score','Pages',0],['worm-best','Best',arcadeBest(game.id)||0]],`<div class="arcade-canvas-wrap"><canvas class="arcade-canvas" width="600" height="600"></canvas><div class="canvas-message"><strong>Bookworm</strong><span>Press start to enter the stacks</span></div></div><div class="mobile-pad"><button class="up">↑</button><button class="left">←</button><button class="down">↓</button><button class="right">→</button></div>`,'Arrow keys or WASD · collect loose pages · avoid the margins.');
  const c=arcadeRoot().querySelector('canvas'),x=c.getContext('2d'),msg=arcadeRoot().querySelector('.canvas-message'),actions=document.getElementById('game-actions');actions.innerHTML='<button class="arcade-btn" id="worm-start">Start</button>';
  const n=20,s=30;let worm,dir,next,page,score,timer,running=false;
  const spawn=()=>{do page={x:Math.floor(Math.random()*n),y:Math.floor(Math.random()*n)};while(worm.some(p=>p.x===page.x&&p.y===page.y))};
  function draw(){x.fillStyle='#17131a';x.fillRect(0,0,600,600);x.strokeStyle='rgba(248,242,229,.06)';for(let i=1;i<n;i++){x.beginPath();x.moveTo(i*s,0);x.lineTo(i*s,600);x.stroke();x.beginPath();x.moveTo(0,i*s);x.lineTo(600,i*s);x.stroke()}x.fillStyle='#ed775f';x.fillRect(page.x*s+8,page.y*s+5,14,20);x.fillStyle='#251d27';x.fillRect(page.x*s+13,page.y*s+5,2,20);worm.forEach((p,i)=>{x.fillStyle=i?'#d7e761':'#ed775f';x.fillRect(p.x*s+3,p.y*s+3,24,24);x.strokeStyle='#251d27';x.strokeRect(p.x*s+7,p.y*s+7,16,13)});}
  function tick(){dir=next;const h={x:worm[0].x+dir.x,y:worm[0].y+dir.y};if(h.x<0||h.y<0||h.x>=n||h.y>=n||worm.some(p=>p.x===h.x&&p.y===h.y))return end();worm.unshift(h);if(h.x===page.x&&h.y===page.y){score++;document.getElementById('worm-score').textContent=score;spawn();clearInterval(timer);timer=setInterval(tick,Math.max(65,145-score*4))}else worm.pop();draw()}
  function start(){clearInterval(timer);worm=[{x:9,y:10},{x:8,y:10},{x:7,y:10}];dir=next={x:1,y:0};score=0;running=true;spawn();draw();msg.hidden=true;actions.querySelector('button').textContent='Restart';timer=setInterval(tick,145)}
  function end(){running=false;clearInterval(timer);saveArcadeBest(game.id,score);document.getElementById('worm-best').textContent=arcadeBest(game.id)||0;msg.hidden=false;msg.innerHTML=`<strong>Margins reached</strong><span>${score} loose page${score===1?'':'s'} collected</span>`}
  function steer(dx,dy){if(!running||dir.x===-dx&&dir.y===-dy)return;next={x:dx,y:dy}}
  const key=e=>{const m={ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1],ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0]}[e.key];if(m){e.preventDefault();steer(...m)}};window.addEventListener('keydown',key);onCleanup(()=>{window.removeEventListener('keydown',key);clearInterval(timer)});actions.querySelector('button').onclick=start;[['.up',0,-1],['.down',0,1],['.left',-1,0],['.right',1,0]].forEach(([q,a,b])=>arcadeRoot().querySelector(q).onclick=()=>steer(a,b));draw();
}

function shelfBreaker(game){
  gameShell(game,[['shelf-score','Score',0],['shelf-lives','Lives',3],['shelf-level','Level',1],['shelf-best','Best',arcadeBest(game.id)||0]],`<div class="arcade-canvas-wrap wide"><canvas class="arcade-canvas" width="720" height="540"></canvas><div class="canvas-message"><strong>Shelf Breaker</strong><span>Clear every shelf</span></div></div>`,'Move with the mouse, touch, or A / D. Space pauses.');
  const c=arcadeRoot().querySelector('canvas'),ctx=c.getContext('2d'),msg=arcadeRoot().querySelector('.canvas-message'),actions=document.getElementById('game-actions');actions.innerHTML='<button class="arcade-btn" id="break-start">Start</button><button class="arcade-btn secondary" id="break-pause">Pause</button>';
  let paddle=310,ball,books=[],score=0,lives=3,level=1,raf=0,running=false,paused=false,last=0;
  function layout(){books=[];const rows=2+level,cols=level===2?9:8;for(let r=0;r<rows;r++)for(let q=0;q<cols;q++)if(level!==3||(r+q)%4!==0)books.push({x:42+q*(636/cols),y:55+r*34,w:636/cols-7,h:25,hit:false,c:(r+q)%2})}
  function resetBall(){ball={x:360,y:460,vx:(Math.random()>.5?1:-1)*220,vy:-260}}
  function paint(){ctx.fillStyle='#17131a';ctx.fillRect(0,0,720,540);books.forEach(b=>{if(b.hit)return;ctx.fillStyle=b.c?'#ed775f':'#d7e761';ctx.fillRect(b.x,b.y,b.w,b.h);ctx.fillStyle='#251d27';ctx.fillRect(b.x+6,b.y+4,2,b.h-8);ctx.fillRect(b.x+b.w-9,b.y+4,3,b.h-8)});ctx.fillStyle='#f8f2e5';ctx.fillRect(paddle,500,100,12);ctx.fillStyle='#ed775f';ctx.beginPath();ctx.arc(ball.x,ball.y,7,0,Math.PI*2);ctx.fill();}
  function frame(t){if(!running)return;if(!paused&&last){const d=Math.min(.025,(t-last)/1000);ball.x+=ball.vx*d;ball.y+=ball.vy*d;if(ball.x<7||ball.x>713)ball.vx*=-1;if(ball.y<7)ball.vy=Math.abs(ball.vy);if(ball.y>490&&ball.y<510&&ball.x>paddle&&ball.x<paddle+100){ball.vy=-Math.abs(ball.vy);ball.vx+=(ball.x-(paddle+50))*3}for(const b of books){if(!b.hit&&ball.x>b.x&&ball.x<b.x+b.w&&ball.y>b.y&&ball.y<b.y+b.h){b.hit=true;ball.vy*=-1;score+=10;document.getElementById('shelf-score').textContent=score;break}}if(books.every(b=>b.hit)){level++;if(level>3)return finish(true);document.getElementById('shelf-level').textContent=level;layout();resetBall()}if(ball.y>550){lives--;document.getElementById('shelf-lives').textContent=lives;if(!lives)return finish(false);resetBall()}}paint();last=t;raf=requestAnimationFrame(frame)}
  function start(){cancelAnimationFrame(raf);score=0;lives=3;level=1;paddle=310;layout();resetBall();running=true;paused=false;last=0;msg.hidden=true;['shelf-score','shelf-level'].forEach((id,i)=>document.getElementById(id).textContent=i?1:0);document.getElementById('shelf-lives').textContent=3;actions.querySelector('#break-start').textContent='Restart';raf=requestAnimationFrame(frame)}
  function finish(win){running=false;cancelAnimationFrame(raf);saveArcadeBest(game.id,score);document.getElementById('shelf-best').textContent=arcadeBest(game.id)||0;msg.hidden=false;msg.innerHTML=`<strong>${win?'Shelves cleared':'Last life lost'}</strong><span>${score} points</span>`}
  function move(clientX){const r=c.getBoundingClientRect();paddle=Math.max(0,Math.min(620,(clientX-r.left)/r.width*720-50))}const mouse=e=>move(e.clientX),touch=e=>{e.preventDefault();move(e.touches[0].clientX)},key=e=>{if(e.key==='a'||e.key==='ArrowLeft')paddle=Math.max(0,paddle-30);if(e.key==='d'||e.key==='ArrowRight')paddle=Math.min(620,paddle+30);if(e.code==='Space'){e.preventDefault();paused=!paused}};c.addEventListener('mousemove',mouse);c.addEventListener('touchmove',touch,{passive:false});window.addEventListener('keydown',key);onCleanup(()=>{cancelAnimationFrame(raf);c.removeEventListener('mousemove',mouse);c.removeEventListener('touchmove',touch);window.removeEventListener('keydown',key)});actions.querySelector('#break-start').onclick=start;actions.querySelector('#break-pause').onclick=()=>{paused=!paused};layout();resetBall();paint();
}

async function coverMatch(game){
  gameShell(game,[['match-moves','Moves',0],['match-time','Time','0:00'],['match-best','Best',arcadeBest(game.id)||'—']],'<div class="match-grid"><p>Pulling covers from the catalogue…</p></div>','Match every pair. Best is the fewest moves.');document.getElementById('game-actions').innerHTML='<button class="arcade-btn" id="match-new">New game</button>';let timer,start,flipped=[],moves=0,lock=false,cards=[];
  async function begin(){clearInterval(timer);const books=shuffle(await getArcadeCatalog()).slice(0,8);const grid=arcadeRoot().querySelector('.match-grid');if(books.length<6){grid.innerHTML='<p>The catalogue is unavailable. Try again when online.</p>';return}cards=shuffle([...books,...books].map((b,i)=>({b,id:`${normalizeText(b.title)}-${i<books.length?0:1}`})));grid.innerHTML=cards.map((c,i)=>`<button class="match-card" data-i="${i}" aria-label="Hidden book cover"><span class="match-inner"><span class="match-face match-back">L</span><span class="match-face match-front">${coverMarkup(c.b)}</span></span></button>`).join('');moves=0;flipped=[];lock=false;start=Date.now();document.getElementById('match-moves').textContent=0;timer=setInterval(()=>document.getElementById('match-time').textContent=`${Math.floor((Date.now()-start)/60000)}:${String(Math.floor((Date.now()-start)/1000)%60).padStart(2,'0')}`,1000);grid.querySelectorAll('.match-card').forEach(el=>el.onclick=()=>flip(el))}
  function flip(el){if(lock||el.classList.contains('flipped')||el.classList.contains('matched'))return;el.classList.add('flipped');flipped.push(el);if(flipped.length<2)return;moves++;document.getElementById('match-moves').textContent=moves;const [a,b]=flipped;if(normalizeText(cards[a.dataset.i].b.title)===normalizeText(cards[b.dataset.i].b.title)){a.classList.add('matched');b.classList.add('matched');flipped=[];if(arcadeRoot().querySelectorAll('.matched').length===cards.length)complete()}else{lock=true;setTimeout(()=>{a.classList.remove('flipped');b.classList.remove('flipped');flipped=[];lock=false},700)}}
  function complete(){clearInterval(timer);saveArcadeBest(game.id,moves,true);document.getElementById('match-best').textContent=arcadeBest(game.id);const sec=Math.floor((Date.now()-start)/1000);arcadeRoot().insertAdjacentHTML('beforeend',`<div class="arcade-dialog"><div class="arcade-dialog-card"><span class="arcade-label">All pairs found</span><h2>Perfect recall.</h2><p>${moves} moves in ${sec} seconds.</p><button class="arcade-btn">Play again</button></div></div>`);arcadeRoot().querySelector('.arcade-dialog button').onclick=()=>{arcadeRoot().querySelector('.arcade-dialog').remove();begin()}}
  onCleanup(()=>clearInterval(timer));document.getElementById('match-new').onclick=begin;begin();
}

async function guessCover(game){
  gameShell(game,[['guess-score','Score',0],['guess-left','Guesses',5],['guess-best','Best',arcadeBest(game.id)||0]],'<div class="guess-stage"><div class="guess-cover" id="guess-cover"></div><div class="guess-form"><span class="arcade-label">Name that book</span><h2 id="guess-prompt">The cover knows the answer.</h2><input id="guess-input" placeholder="Type the title…" autocomplete="off"><div class="game-actions"><button class="arcade-btn" id="guess-submit">Submit</button><button class="arcade-btn secondary" id="guess-skip">Skip</button><button class="arcade-btn" id="guess-next" hidden>Next book</button></div><p class="guess-feedback" id="guess-feedback"></p></div></div>','Punctuation and capitalisation do not count against you.');
  let books=shuffle(await getArcadeCatalog()),book,tries,ended,score=0,index=0;const input=document.getElementById('guess-input'),feedback=document.getElementById('guess-feedback');
  function next(){book=books[index++%books.length];tries=0;ended=false;document.getElementById('guess-left').textContent=5;document.getElementById('guess-cover').innerHTML=coverMarkup(book);document.getElementById('guess-cover').querySelector('img').style.filter='blur(22px) saturate(.5)';input.value='';input.disabled=false;feedback.textContent='';document.getElementById('guess-submit').hidden=false;document.getElementById('guess-skip').hidden=false;document.getElementById('guess-next').hidden=true;input.focus()}
  function norm(s){return normalizeText(s).replace(/\b(the|a|an)\b/g,'').replace(/[^a-z0-9]/g,'')}
  function finish(ok){ended=true;const earned=ok?(5-tries)*25+25:0;score+=earned;saveArcadeBest(game.id,score);document.getElementById('guess-score').textContent=score;document.getElementById('guess-best').textContent=arcadeBest(game.id)||0;const img=document.getElementById('guess-cover').querySelector('img');if(img)img.style.filter='none';feedback.textContent=ok?`Correct — ${book.title} by ${book.author}. +${earned}`:`It was ${book.title} by ${book.author}.`;input.disabled=true;document.getElementById('guess-submit').hidden=true;document.getElementById('guess-skip').hidden=true;document.getElementById('guess-next').hidden=false}
  function submit(){if(ended||!input.value.trim())return;if(norm(input.value)===norm(book.title))finish(true);else{tries++;document.getElementById('guess-left').textContent=5-tries;feedback.textContent=tries<5?'Not quite. The cover is a little clearer.':'';const img=document.getElementById('guess-cover').querySelector('img');if(img)img.style.filter=`blur(${Math.max(2,22-tries*4)}px) saturate(${.5+tries*.1})`;if(tries>=5)finish(false)}}
  document.getElementById('guess-submit').onclick=submit;document.getElementById('guess-skip').onclick=()=>finish(false);document.getElementById('guess-next').onclick=next;input.onkeydown=e=>{if(e.key==='Enter')submit()};if(books.length)next();else feedback.textContent='The catalogue is unavailable. Try again when online.';
}

async function firstEdition(game){
  gameShell(game,[['edition-streak','Streak',0],['edition-correct','Correct',0],['edition-wrong','Wrong',0],['edition-best','Best',arcadeBest(game.id)||0]],'<div class="edition-prompt"><span class="arcade-label">Round <b id="edition-round">01</b></span><h2>Which was published first?</h2><p id="edition-result" aria-live="polite">Choose the book you think reached readers first.</p></div><div class="edition-pair" id="edition-pair"></div>','Choose a cover. Both publication years are revealed after your answer.');document.getElementById('game-actions').innerHTML='<button class="arcade-btn" id="edition-next" hidden>Next round →</button><button class="arcade-btn secondary" id="edition-restart">Restart</button>';
  let books=shuffle(await getArcadeCatalog(true)),pair=[],streak=0,correct=0,wrong=0,answered=false,round=0,nextTimer;
  function next(){answered=false;round++;for(let i=0;i<30;i++){pair=shuffle([...books]).slice(0,2);if(pair.length===2&&+pair[0].year!==+pair[1].year)break}document.getElementById('edition-round').textContent=String(round).padStart(2,'0');document.getElementById('edition-result').textContent='Choose the book you think reached readers first.';document.getElementById('edition-result').className='';document.getElementById('edition-next').hidden=true;document.getElementById('edition-pair').innerHTML=pair.map((b,i)=>`<button class="edition-card" data-i="${i}"><span class="edition-cover">${coverMarkup(b)}</span><span class="edition-copy"><span class="edition-choice">Choice ${String.fromCharCode(65+i)}</span><h2>${escHtml(b.title)}</h2><p>${escHtml(b.author||'Unknown author')}</p><b class="edition-year" hidden>${b.year}</b><em class="edition-verdict"></em></span></button>${i===0?'<span class="edition-vs" aria-hidden="true">VS</span>':''}`).join('');document.querySelectorAll('.edition-card').forEach(c=>c.onclick=()=>choose(+c.dataset.i))}
  function choose(i){if(answered)return;answered=true;const earlier=+pair[0].year<+pair[1].year?0:1,ok=i===earlier;document.querySelectorAll('.edition-year').forEach(e=>e.hidden=false);document.querySelectorAll('.edition-card').forEach((c,j)=>{c.classList.add(j===earlier?'correct':j===i?'wrong':'dimmed');c.querySelector('.edition-verdict').textContent=j===earlier?'Published first':j===i?'Your choice':''});if(ok){streak++;correct++;saveArcadeBest(game.id,streak)}else{streak=0;wrong++}const result=document.getElementById('edition-result');result.textContent=ok?'Correct. You found the older book.':`${pair[earlier].title} was published first.`;result.className=ok?'is-correct':'is-wrong';document.getElementById('edition-streak').textContent=streak;document.getElementById('edition-correct').textContent=correct;document.getElementById('edition-wrong').textContent=wrong;document.getElementById('edition-best').textContent=arcadeBest(game.id)||0;clearTimeout(nextTimer);nextTimer=setTimeout(()=>document.getElementById('edition-next').hidden=false,700)}
  function restart(){streak=correct=wrong=round=0;['edition-streak','edition-correct','edition-wrong'].forEach(id=>document.getElementById(id).textContent=0);next()}onCleanup(()=>clearTimeout(nextTimer));document.getElementById('edition-next').onclick=next;document.getElementById('edition-restart').onclick=restart;if(books.length>=2)next();else document.getElementById('edition-pair').innerHTML='<p>The catalogue has no dated covers available right now.</p>';
}
