// Fallback hardcoded list IDs for offline mode
const CURATED_LIST_IDS = ['lemonde', 'modernlibrary', 'telegraph', 'bbc', 'time', 'guardian'];

const CURATED_LISTS_OFFLINE = {
  lemonde: {
    title: "Le Monde's 100 Books of the Century",
    source: "Le Monde",
    year: "1999",
    desc: "In 1999, the French newspaper Le Monde asked its readers to vote for the greatest books of the 20th century. The result was a fascinating cross-section of world literature.",
    books: [
      { title: "In Search of Lost Time", author: "Marcel Proust" },
      { title: "The Trial", author: "Franz Kafka" },
      { title: "Journey to the End of the Night", author: "Louis-Ferdinand Céline" },
      { title: "The Stranger", author: "Albert Camus" },
      { title: "Ulysses", author: "James Joyce" },
      { title: "The Little Prince", author: "Antoine de Saint-Exupéry" },
      { title: "One Hundred Years of Solitude", author: "Gabriel García Márquez" },
      { title: "The Great Gatsby", author: "F. Scott Fitzgerald" },
      { title: "The Sound and the Fury", author: "William Faulkner" },
      { title: "Brave New World", author: "Aldous Huxley" },
      { title: "The Master and Margarita", author: "Mikhail Bulgakov" },
      { title: "The Grapes of Wrath", author: "John Steinbeck" },
      { title: "Lolita", author: "Vladimir Nabokov" },
      { title: "The Plague", author: "Albert Camus" },
      { title: "Nausea", author: "Jean-Paul Sartre" },
      { title: "Waiting for Godot", author: "Samuel Beckett" },
      { title: "The Tin Drum", author: "Günter Grass" },
      { title: "The Old Man and the Sea", author: "Ernest Hemingway" },
      { title: "Lord of the Flies", author: "William Golding" },
      { title: "Nineteen Eighty-Four", author: "George Orwell" },
      { title: "For Whom the Bell Tolls", author: "Ernest Hemingway" },
      { title: "The Name of the Rose", author: "Umberto Eco" },
      { title: "Gone with the Wind", author: "Margaret Mitchell" },
      { title: "The Diary of a Young Girl", author: "Anne Frank" },
      { title: "The Second Sex", author: "Simone de Beauvoir" },
      { title: "If This Is a Man", author: "Primo Levi" },
      { title: "The Leopard", author: "Giuseppe Tomasi di Lampedusa" },
      { title: "Doctor Zhivago", author: "Boris Pasternak" },
      { title: "The Tropic of Cancer", author: "Henry Miller" },
      { title: "Man's Fate", author: "André Malraux" },
      { title: "Being and Nothingness", author: "Jean-Paul Sartre" },
      { title: "A Room of One's Own", author: "Virginia Woolf" },
      { title: "The Counterfeiters", author: "André Gide" },
      { title: "The Lover", author: "Marguerite Duras" },
      { title: "Les Enfants Terribles", author: "Jean Cocteau" },
      { title: "Beloved", author: "Toni Morrison" },
      { title: "Catch-22", author: "Joseph Heller" },
      { title: "The Catcher in the Rye", author: "J.D. Salinger" },
      { title: "To Kill a Mockingbird", author: "Harper Lee" },
      { title: "Invisible Man", author: "Ralph Ellison" },
      { title: "On the Road", author: "Jack Kerouac" },
      { title: "Ficciones", author: "Jorge Luis Borges" },
      { title: "The Unbearable Lightness of Being", author: "Milan Kundera" },
      { title: "The Metamorphosis", author: "Franz Kafka" },
      { title: "To the Lighthouse", author: "Virginia Woolf" },
      { title: "Mrs Dalloway", author: "Virginia Woolf" },
      { title: "The Bell Jar", author: "Sylvia Plath" },
      { title: "Steppenwolf", author: "Hermann Hesse" },
      { title: "Siddhartha", author: "Hermann Hesse" },
      { title: "The Glass Bead Game", author: "Hermann Hesse" },
      { title: "Things Fall Apart", author: "Chinua Achebe" },
      { title: "Animal Farm", author: "George Orwell" },
      { title: "A Farewell to Arms", author: "Ernest Hemingway" },
      { title: "Death in Venice", author: "Thomas Mann" },
      { title: "The Magic Mountain", author: "Thomas Mann" },
      { title: "Buddenbrooks", author: "Thomas Mann" },
      { title: "All Quiet on the Western Front", author: "Erich Maria Remarque" },
      { title: "Berlin Alexanderplatz", author: "Alfred Döblin" },
      { title: "Nadja", author: "André Breton" },
      { title: "The Tartar Steppe", author: "Dino Buzzati" },
      { title: "The Stranger", author: "Albert Camus" },
      { title: "The Myth of Sisyphus", author: "Albert Camus" },
      { title: "No Exit", author: "Jean-Paul Sartre" },
      { title: "The Mandarins", author: "Simone de Beauvoir" },
      { title: "Memoirs of Hadrian", author: "Marguerite Yourcenar" },
      { title: "Zazie in the Metro", author: "Raymond Queneau" },
      { title: "The Ravishing of Lol Stein", author: "Marguerite Duras" },
      { title: "Tropism", author: "Nathalie Sarraute" },
      { title: "A Void", author: "Georges Perec" },
      { title: "Life: A User's Manual", author: "Georges Perec" },
      { title: "W, or the Memory of Childhood", author: "Georges Perec" },
      { title: "The Opposing Shore", author: "Julien Gracq" },
      { title: "Friday", author: "Michel Tournier" },
      { title: "Bonjour Tristesse", author: "Françoise Sagan" },
      { title: "Thérèse Desqueyroux", author: "François Mauriac" },
      { title: "The Horseman on the Roof", author: "Jean Giono" },
      { title: "Strait Is the Gate", author: "André Gide" },
      { title: "The Immoralist", author: "André Gide" },
      { title: "The Voyeur", author: "Alain Robbe-Grillet" },
      { title: "Jealousy", author: "Alain Robbe-Grillet" },
      { title: "The Erasers", author: "Alain Robbe-Grillet" },
      { title: "Moderato Cantabile", author: "Marguerite Duras" },
      { title: "The Wind", author: "Claude Simon" },
      { title: "The Flanders Road", author: "Claude Simon" },
      { title: "The Bald Soprano", author: "Eugène Ionesco" },
      { title: "Rhinoceros", author: "Eugène Ionesco" },
      { title: "Endgame", author: "Samuel Beckett" },
      { title: "Molloy", author: "Samuel Beckett" },
      { title: "The Unnamable", author: "Samuel Beckett" },
      { title: "The Roots of Heaven", author: "Romain Gary" },
      { title: "Promise at Dawn", author: "Romain Gary" },
      { title: "The Life Before Us", author: "Romain Gary" },
      { title: "Gargantua and Pantagruel", author: "François Rabelais" },
      { title: "Germinal", author: "Émile Zola" },
      { title: "Les Misérables", author: "Victor Hugo" },
      { title: "Madame Bovary", author: "Gustave Flaubert" },
      { title: "The Red and the Black", author: "Stendhal" },
      { title: "The Count of Monte Cristo", author: "Alexandre Dumas" },
      { title: "Cyrano de Bergerac", author: "Edmond Rostand" },
    ]
  },
  modernlibrary: {
    title: "Modern Library 100 Best Novels",
    source: "Modern Library",
    year: "1998",
    desc: "The board's selection of the 100 best English-language novels published since 1900. A canonical list that has sparked endless debate since its publication.",
    books: [
      { title: "Ulysses", author: "James Joyce" },
      { title: "The Great Gatsby", author: "F. Scott Fitzgerald" },
      { title: "A Portrait of the Artist as a Young Man", author: "James Joyce" },
      { title: "Lolita", author: "Vladimir Nabokov" },
      { title: "Brave New World", author: "Aldous Huxley" },
      { title: "The Sound and the Fury", author: "William Faulkner" },
      { title: "Catch-22", author: "Joseph Heller" },
      { title: "Darkness at Noon", author: "Arthur Koestler" },
      { title: "Sons and Lovers", author: "D.H. Lawrence" },
      { title: "The Grapes of Wrath", author: "John Steinbeck" },
      { title: "Under the Volcano", author: "Malcolm Lowry" },
      { title: "The Way of All Flesh", author: "Samuel Butler" },
      { title: "1984", author: "George Orwell" },
      { title: "I, Claudius", author: "Robert Graves" },
      { title: "To the Lighthouse", author: "Virginia Woolf" },
      { title: "An American Tragedy", author: "Theodore Dreiser" },
      { title: "The Heart Is a Lonely Hunter", author: "Carson McCullers" },
      { title: "Slaughterhouse-Five", author: "Kurt Vonnegut" },
      { title: "Invisible Man", author: "Ralph Ellison" },
      { title: "Native Son", author: "Richard Wright" },
      { title: "Henderson the Rain King", author: "Saul Bellow" },
      { title: "Appointment in Samarra", author: "John O'Hara" },
      { title: "U.S.A. Trilogy", author: "John Dos Passos" },
      { title: "Winesburg, Ohio", author: "Sherwood Anderson" },
      { title: "A Passage to India", author: "E.M. Forster" },
      { title: "The Wings of the Dove", author: "Henry James" },
      { title: "The Ambassadors", author: "Henry James" },
      { title: "Tender Is the Night", author: "F. Scott Fitzgerald" },
      { title: "The Studs Lonigan Trilogy", author: "James T. Farrell" },
      { title: "The Good Soldier", author: "Ford Madox Ford" },
      { title: "Animal Farm", author: "George Orwell" },
      { title: "The Golden Bowl", author: "Henry James" },
      { title: "Sister Carrie", author: "Theodore Dreiser" },
      { title: "A Handful of Dust", author: "Evelyn Waugh" },
      { title: "As I Lay Dying", author: "William Faulkner" },
      { title: "All the King's Men", author: "Robert Penn Warren" },
      { title: "The Bridge of San Luis Rey", author: "Thornton Wilder" },
      { title: "Howards End", author: "E.M. Forster" },
      { title: "Go Tell It on the Mountain", author: "James Baldwin" },
      { title: "The Heart of the Matter", author: "Graham Greene" },
      { title: "Lord of the Flies", author: "William Golding" },
      { title: "Deliverance", author: "James Dickey" },
      { title: "A Dance to the Music of Time", author: "Anthony Powell" },
      { title: "Point Counter Point", author: "Aldous Huxley" },
      { title: "The Sun Also Rises", author: "Ernest Hemingway" },
      { title: "The Secret Agent", author: "Joseph Conrad" },
      { title: "Nostromo", author: "Joseph Conrad" },
      { title: "The Rainbow", author: "D.H. Lawrence" },
      { title: "Women in Love", author: "D.H. Lawrence" },
      { title: "Tropic of Cancer", author: "Henry Miller" },
      { title: "The Naked and the Dead", author: "Norman Mailer" },
      { title: "Portnoy's Complaint", author: "Philip Roth" },
      { title: "Pale Fire", author: "Vladimir Nabokov" },
      { title: "Light in August", author: "William Faulkner" },
      { title: "On the Road", author: "Jack Kerouac" },
      { title: "The Maltese Falcon", author: "Dashiell Hammett" },
      { title: "Parade's End", author: "Ford Madox Ford" },
      { title: "The Age of Innocence", author: "Edith Wharton" },
      { title: "Zuleika Dobson", author: "Max Beerbohm" },
      { title: "The Moviegoer", author: "Walker Percy" },
      { title: "Death Comes for the Archbishop", author: "Willa Cather" },
      { title: "From Here to Eternity", author: "James Jones" },
      { title: "The Wapshot Chronicles", author: "John Cheever" },
      { title: "The Catcher in the Rye", author: "J.D. Salinger" },
      { title: "A Clockwork Orange", author: "Anthony Burgess" },
      { title: "Of Human Bondage", author: "W. Somerset Maugham" },
      { title: "Heart of Darkness", author: "Joseph Conrad" },
      { title: "Main Street", author: "Sinclair Lewis" },
      { title: "The House of Mirth", author: "Edith Wharton" },
      { title: "The Alexandria Quartet", author: "Lawrence Durrell" },
      { title: "A High Wind in Jamaica", author: "Richard Hughes" },
      { title: "A House for Mr Biswas", author: "V.S. Naipaul" },
      { title: "The Day of the Locust", author: "Nathanael West" },
      { title: "A Farewell to Arms", author: "Ernest Hemingway" },
      { title: "Scoop", author: "Evelyn Waugh" },
      { title: "The Prime of Miss Jean Brodie", author: "Muriel Spark" },
      { title: "Finnegans Wake", author: "James Joyce" },
      { title: "Kim", author: "Rudyard Kipling" },
      { title: "A Room with a View", author: "E.M. Forster" },
      { title: "Brideshead Revisited", author: "Evelyn Waugh" },
      { title: "The Adventures of Augie March", author: "Saul Bellow" },
      { title: "Angle of Repose", author: "Wallace Stegner" },
      { title: "A Bend in the River", author: "V.S. Naipaul" },
      { title: "The Death of the Heart", author: "Elizabeth Bowen" },
      { title: "Lord Jim", author: "Joseph Conrad" },
      { title: "Ragtime", author: "E.L. Doctorow" },
      { title: "The Old Wives' Tale", author: "Arnold Bennett" },
      { title: "The Call of the Wild", author: "Jack London" },
      { title: "Loving", author: "Henry Green" },
      { title: "Midnight's Children", author: "Salman Rushdie" },
      { title: "Tobacco Road", author: "Erskine Caldwell" },
      { title: "Ironweed", author: "William Kennedy" },
      { title: "The Magus", author: "John Fowles" },
      { title: "Wide Sargasso Sea", author: "Jean Rhys" },
      { title: "Under the Net", author: "Iris Murdoch" },
      { title: "Sophie's Choice", author: "William Styron" },
      { title: "The Sheltering Sky", author: "Paul Bowles" },
      { title: "The Postman Always Rings Twice", author: "James M. Cain" },
      { title: "The Ginger Man", author: "J.P. Donleavy" },
      { title: "The Magnificent Ambersons", author: "Booth Tarkington" },
    ]
  },
  telegraph: {
    title: "The Telegraph's Greatest Villains in Literature",
    source: "The Telegraph",
    year: "2008",
    desc: "The most compelling, chilling and unforgettable antagonists ever committed to the page — the books that gave us literature's greatest monsters.",
    books: [
      { title: "Lolita", author: "Vladimir Nabokov" },
      { title: "Crime and Punishment", author: "Fyodor Dostoevsky" },
      { title: "American Psycho", author: "Bret Easton Ellis" },
      { title: "We Need to Talk About Kevin", author: "Lionel Shriver" },
      { title: "Perfume", author: "Patrick Süskind" },
      { title: "The Talented Mr Ripley", author: "Patricia Highsmith" },
      { title: "Rebecca", author: "Daphne du Maurier" },
      { title: "No Country for Old Men", author: "Cormac McCarthy" },
      { title: "The Silence of the Lambs", author: "Thomas Harris" },
      { title: "Frankenstein", author: "Mary Shelley" },
      { title: "Blood Meridian", author: "Cormac McCarthy" },
      { title: "The Picture of Dorian Gray", author: "Oscar Wilde" },
      { title: "Dracula", author: "Bram Stoker" },
      { title: "Gone Girl", author: "Gillian Flynn" },
      { title: "Nineteen Eighty-Four", author: "George Orwell" },
      { title: "A Clockwork Orange", author: "Anthony Burgess" },
      { title: "The Shining", author: "Stephen King" },
      { title: "Lord of the Flies", author: "William Golding" },
      { title: "Misery", author: "Stephen King" },
      { title: "Battle Royale", author: "Koushun Takami" },
      { title: "Wuthering Heights", author: "Emily Brontë" },
      { title: "Othello", author: "William Shakespeare" },
      { title: "Paradise Lost", author: "John Milton" },
      { title: "The Count of Monte Cristo", author: "Alexandre Dumas" },
      { title: "Great Expectations", author: "Charles Dickens" },
      { title: "Oliver Twist", author: "Charles Dickens" },
      { title: "The Strange Case of Dr Jekyll and Mr Hyde", author: "Robert Louis Stevenson" },
      { title: "Moby-Dick", author: "Herman Melville" },
      { title: "The Phantom of the Opera", author: "Gaston Leroux" },
      { title: "The Hound of the Baskervilles", author: "Arthur Conan Doyle" },
      { title: "Heart of Darkness", author: "Joseph Conrad" },
      { title: "The Turn of the Screw", author: "Henry James" },
      { title: "One Flew Over the Cuckoo's Nest", author: "Ken Kesey" },
      { title: "The Collector", author: "John Fowles" },
      { title: "Rosemary's Baby", author: "Ira Levin" },
      { title: "The Exorcist", author: "William Peter Blatty" },
      { title: "The Omen", author: "David Seltzer" },
      { title: "Carrie", author: "Stephen King" },
      { title: "It", author: "Stephen King" },
      { title: "Pet Sematary", author: "Stephen King" },
      { title: "The Stand", author: "Stephen King" },
      { title: "Hannibal", author: "Thomas Harris" },
      { title: "Red Dragon", author: "Thomas Harris" },
      { title: "The Girl with the Dragon Tattoo", author: "Stieg Larsson" },
      { title: "Sharp Objects", author: "Gillian Flynn" },
      { title: "The Secret History", author: "Donna Tartt" },
      { title: "And Then There Were None", author: "Agatha Christie" },
      { title: "The Murder of Roger Ackroyd", author: "Agatha Christie" },
      { title: "In Cold Blood", author: "Truman Capote" },
      { title: "The Talented Mr. Ripley", author: "Patricia Highsmith" },
      { title: "A Good Man Is Hard to Find", author: "Flannery O'Connor" },
      { title: "The Wasp Factory", author: "Iain Banks" },
      { title: "Atonement", author: "Ian McEwan" },
      { title: "Enduring Love", author: "Ian McEwan" },
      { title: "The Comfort of Strangers", author: "Ian McEwan" },
      { title: "The Haunting of Hill House", author: "Shirley Jackson" },
      { title: "We Have Always Lived in the Castle", author: "Shirley Jackson" },
      { title: "Something Wicked This Way Comes", author: "Ray Bradbury" },
      { title: "The Island of Doctor Moreau", author: "H.G. Wells" },
      { title: "The Invisible Man", author: "H.G. Wells" },
      { title: "The War of the Worlds", author: "H.G. Wells" },
      { title: "Do Androids Dream of Electric Sheep?", author: "Philip K. Dick" },
      { title: "The Stepford Wives", author: "Ira Levin" },
      { title: "The Boys from Brazil", author: "Ira Levin" },
      { title: "Psycho", author: "Robert Bloch" },
      { title: "The Phantom of the Opera", author: "Gaston Leroux" },
      { title: "The Monk", author: "Matthew Lewis" },
      { title: "The Castle of Otranto", author: "Horace Walpole" },
      { title: "The Mysteries of Udolpho", author: "Ann Radcliffe" },
      { title: "Northanger Abbey", author: "Jane Austen" },
      { title: "Jane Eyre", author: "Charlotte Brontë" },
      { title: "Villette", author: "Charlotte Brontë" },
      { title: "The Woman in White", author: "Wilkie Collins" },
      { title: "The Moonstone", author: "Wilkie Collins" },
      { title: "Bleak House", author: "Charles Dickens" },
      { title: "A Tale of Two Cities", author: "Charles Dickens" },
      { title: "The Hunchback of Notre-Dame", author: "Victor Hugo" },
      { title: "Les Misérables", author: "Victor Hugo" },
      { title: "The Brothers Karamazov", author: "Fyodor Dostoevsky" },
      { title: "Notes from Underground", author: "Fyodor Dostoevsky" },
      { title: "Dead Souls", author: "Nikolai Gogol" },
      { title: "Anna Karenina", author: "Leo Tolstoy" },
      { title: "War and Peace", author: "Leo Tolstoy" },
      { title: "The Master and Margarita", author: "Mikhail Bulgakov" },
      { title: "Child of God", author: "Cormac McCarthy" },
      { title: "Outer Dark", author: "Cormac McCarthy" },
      { title: "The Road", author: "Cormac McCarthy" },
      { title: "Under the Skin", author: "Michel Faber" },
      { title: "The Dice Man", author: "Luke Rhinehart" },
      { title: "Filth", author: "Irvine Welsh" },
      { title: "Trainspotting", author: "Irvine Welsh" },
      { title: "The Killer Inside Me", author: "Jim Thompson" },
      { title: "The Getaway", author: "Jim Thompson" },
      { title: "Clockers", author: "Richard Price" },
      { title: "The Devil All the Time", author: "Donald Ray Pollock" },
      { title: "Tampa", author: "Alissa Nutting" },
      { title: "You", author: "Caroline Kepnes" },
      { title: "My Year of Rest and Relaxation", author: "Ottessa Moshfegh" },
      { title: "Apt Pupil", author: "Stephen King" },
    ]
  },
  bbc: {
    title: "BBC's 100 Novels That Shaped Our World",
    source: "BBC",
    year: "2019",
    desc: "A celebration of fiction that has had a profound impact on culture, society and our understanding of what it means to be human.",
    books: [
      { title: "Frankenstein", author: "Mary Shelley" },
      { title: "Jane Eyre", author: "Charlotte Brontë" },
      { title: "Middlemarch", author: "George Eliot" },
      { title: "The War of the Worlds", author: "H.G. Wells" },
      { title: "The Great Gatsby", author: "F. Scott Fitzgerald" },
      { title: "Mrs Dalloway", author: "Virginia Woolf" },
      { title: "Brave New World", author: "Aldous Huxley" },
      { title: "Their Eyes Were Watching God", author: "Zora Neale Hurston" },
      { title: "The Second Sex", author: "Simone de Beauvoir" },
      { title: "Nineteen Eighty-Four", author: "George Orwell" },
      { title: "The Catcher in the Rye", author: "J.D. Salinger" },
      { title: "Lord of the Flies", author: "William Golding" },
      { title: "Lolita", author: "Vladimir Nabokov" },
      { title: "To Kill a Mockingbird", author: "Harper Lee" },
      { title: "One Hundred Years of Solitude", author: "Gabriel García Márquez" },
      { title: "The Female Eunuch", author: "Germaine Greer" },
      { title: "Watership Down", author: "Richard Adams" },
      { title: "The Hitchhiker's Guide to the Galaxy", author: "Douglas Adams" },
      { title: "If on a winter's night a traveler", author: "Italo Calvino" },
      { title: "The Color Purple", author: "Alice Walker" },
      { title: "Beloved", author: "Toni Morrison" },
      { title: "A Room of One's Own", author: "Virginia Woolf" },
      { title: "Things Fall Apart", author: "Chinua Achebe" },
      { title: "A Clockwork Orange", author: "Anthony Burgess" },
      { title: "Wide Sargasso Sea", author: "Jean Rhys" },
      { title: "Midnight's Children", author: "Salman Rushdie" },
      { title: "The Handmaid's Tale", author: "Margaret Atwood" },
      { title: "The Remains of the Day", author: "Kazuo Ishiguro" },
      { title: "Harry Potter and the Philosopher's Stone", author: "J.K. Rowling" },
      { title: "The Curious Incident of the Dog in the Night-Time", author: "Mark Haddon" },
      { title: "Ulysses", author: "James Joyce" },
      { title: "In Search of Lost Time", author: "Marcel Proust" },
      { title: "The Trial", author: "Franz Kafka" },
      { title: "The Master and Margarita", author: "Mikhail Bulgakov" },
      { title: "Invisible Man", author: "Ralph Ellison" },
      { title: "On the Road", author: "Jack Kerouac" },
      { title: "Catch-22", author: "Joseph Heller" },
      { title: "One Flew Over the Cuckoo's Nest", author: "Ken Kesey" },
      { title: "Slaughterhouse-Five", author: "Kurt Vonnegut" },
      { title: "Song of Solomon", author: "Toni Morrison" },
      { title: "Dracula", author: "Bram Stoker" },
      { title: "Rebecca", author: "Daphne du Maurier" },
      { title: "The Big Sleep", author: "Raymond Chandler" },
      { title: "The Maltese Falcon", author: "Dashiell Hammett" },
      { title: "And Then There Were None", author: "Agatha Christie" },
      { title: "The Spy Who Came in from the Cold", author: "John le Carré" },
      { title: "The Godfather", author: "Mario Puzo" },
      { title: "Gone Girl", author: "Gillian Flynn" },
      { title: "The Girl with the Dragon Tattoo", author: "Stieg Larsson" },
      { title: "Bridget Jones's Diary", author: "Helen Fielding" },
      { title: "Pride and Prejudice", author: "Jane Austen" },
      { title: "Wuthering Heights", author: "Emily Brontë" },
      { title: "Anna Karenina", author: "Leo Tolstoy" },
      { title: "Gone with the Wind", author: "Margaret Mitchell" },
      { title: "The Thorn Birds", author: "Colleen McCullough" },
      { title: "Atonement", author: "Ian McEwan" },
      { title: "Normal People", author: "Sally Rooney" },
      { title: "A Suitable Boy", author: "Vikram Seth" },
      { title: "Persepolis", author: "Marjane Satrapi" },
      { title: "A Brief History of Seven Killings", author: "Marlon James" },
      { title: "The Lord of the Rings", author: "J.R.R. Tolkien" },
      { title: "The Lion, the Witch and the Wardrobe", author: "C.S. Lewis" },
      { title: "Earthsea", author: "Ursula K. Le Guin" },
      { title: "Jonathan Strange & Mr Norrell", author: "Susanna Clarke" },
      { title: "The Hobbit", author: "J.R.R. Tolkien" },
      { title: "His Dark Materials", author: "Philip Pullman" },
      { title: "A Game of Thrones", author: "George R.R. Martin" },
      { title: "Neuromancer", author: "William Gibson" },
      { title: "Do Androids Dream of Electric Sheep?", author: "Philip K. Dick" },
      { title: "The Left Hand of Darkness", author: "Ursula K. Le Guin" },
      { title: "Dune", author: "Frank Herbert" },
      { title: "The Day of the Triffids", author: "John Wyndham" },
      { title: "2001: A Space Odyssey", author: "Arthur C. Clarke" },
      { title: "I, Robot", author: "Isaac Asimov" },
      { title: "Foundation", author: "Isaac Asimov" },
      { title: "Kindred", author: "Octavia E. Butler" },
      { title: "The Jungle Book", author: "Rudyard Kipling" },
      { title: "Winnie-the-Pooh", author: "A.A. Milne" },
      { title: "Alice's Adventures in Wonderland", author: "Lewis Carroll" },
      { title: "Charlie and the Chocolate Factory", author: "Roald Dahl" },
      { title: "Noughts & Crosses", author: "Malorie Blackman" },
      { title: "The Diary of a Young Girl", author: "Anne Frank" },
      { title: "Pippi Longstocking", author: "Astrid Lindgren" },
      { title: "Northern Lights", author: "Philip Pullman" },
      { title: "Little Women", author: "Louisa May Alcott" },
      { title: "Charlotte's Web", author: "E.B. White" },
      { title: "The Wind in the Willows", author: "Kenneth Grahame" },
      { title: "Treasure Island", author: "Robert Louis Stevenson" },
      { title: "Black Beauty", author: "Anna Sewell" },
      { title: "The Secret Garden", author: "Frances Hodgson Burnett" },
      { title: "A Little Princess", author: "Frances Hodgson Burnett" },
      { title: "The Railway Children", author: "E. Nesbit" },
      { title: "Swallows and Amazons", author: "Arthur Ransome" },
      { title: "Ballet Shoes", author: "Noel Streatfeild" },
      { title: "The Borrowers", author: "Mary Norton" },
      { title: "The Phantom Tollbooth", author: "Norton Juster" },
      { title: "The Outsiders", author: "S.E. Hinton" },
      { title: "Roll of Thunder, Hear My Cry", author: "Mildred D. Taylor" },
      { title: "Wolf Hall", author: "Hilary Mantel" },
      { title: "White Teeth", author: "Zadie Smith" },
    ]
  },
  time: {
    title: "TIME's 100 Best Novels",
    source: "TIME Magazine",
    year: "2005",
    desc: "TIME critics Lev Grossman and Richard Lacayo's picks for the 100 best English-language novels from 1923 to the present.",
    books: [
      { title: "Beloved", author: "Toni Morrison" },
      { title: "The Complete Stories", author: "Flannery O'Connor" },
      { title: "The Corrections", author: "Jonathan Franzen" },
      { title: "The Stories of John Cheever", author: "John Cheever" },
      { title: "At Swim-Two-Birds", author: "Flann O'Brien" },
      { title: "Atonement", author: "Ian McEwan" },
      { title: "Blood Meridian", author: "Cormac McCarthy" },
      { title: "Catch-22", author: "Joseph Heller" },
      { title: "A Clockwork Orange", author: "Anthony Burgess" },
      { title: "The Crying of Lot 49", author: "Thomas Pynchon" },
      { title: "Slaughterhouse-Five", author: "Kurt Vonnegut" },
      { title: "To Kill a Mockingbird", author: "Harper Lee" },
      { title: "White Noise", author: "Don DeLillo" },
      { title: "The Lord of the Rings", author: "J.R.R. Tolkien" },
      { title: "Never Let Me Go", author: "Kazuo Ishiguro" },
      { title: "Lolita", author: "Vladimir Nabokov" },
      { title: "The Remains of the Day", author: "Kazuo Ishiguro" },
      { title: "American Pastoral", author: "Philip Roth" },
      { title: "Midnight's Children", author: "Salman Rushdie" },
      { title: "The Road", author: "Cormac McCarthy" },
      { title: "The Great Gatsby", author: "F. Scott Fitzgerald" },
      { title: "A Handful of Dust", author: "Evelyn Waugh" },
      { title: "A House for Mr Biswas", author: "V.S. Naipaul" },
      { title: "In Search of Lost Time", author: "Marcel Proust" },
      { title: "Invisible Man", author: "Ralph Ellison" },
      { title: "Light in August", author: "William Faulkner" },
      { title: "The Lion, the Witch and the Wardrobe", author: "C.S. Lewis" },
      { title: "Money", author: "Martin Amis" },
      { title: "The Moviegoer", author: "Walker Percy" },
      { title: "Mrs Dalloway", author: "Virginia Woolf" },
      { title: "Naked Lunch", author: "William S. Burroughs" },
      { title: "Native Son", author: "Richard Wright" },
      { title: "Neuromancer", author: "William Gibson" },
      { title: "On the Road", author: "Jack Kerouac" },
      { title: "One Flew Over the Cuckoo's Nest", author: "Ken Kesey" },
      { title: "The Painted Bird", author: "Jerzy Kosiński" },
      { title: "Pale Fire", author: "Vladimir Nabokov" },
      { title: "A Passage to India", author: "E.M. Forster" },
      { title: "Play It as It Lays", author: "Joan Didion" },
      { title: "Portnoy's Complaint", author: "Philip Roth" },
      { title: "Possession", author: "A.S. Byatt" },
      { title: "The Power and the Glory", author: "Graham Greene" },
      { title: "The Prime of Miss Jean Brodie", author: "Muriel Spark" },
      { title: "Rabbit, Run", author: "John Updike" },
      { title: "Ragtime", author: "E.L. Doctorow" },
      { title: "The Recognitions", author: "William Gaddis" },
      { title: "Revolutionary Road", author: "Richard Yates" },
      { title: "The Sheltering Sky", author: "Paul Bowles" },
      { title: "Snow Crash", author: "Neal Stephenson" },
      { title: "The Sot-Weed Factor", author: "John Barth" },
      { title: "The Sound and the Fury", author: "William Faulkner" },
      { title: "The Spy Who Came in from the Cold", author: "John le Carré" },
      { title: "The Sun Also Rises", author: "Ernest Hemingway" },
      { title: "Their Eyes Were Watching God", author: "Zora Neale Hurston" },
      { title: "Things Fall Apart", author: "Chinua Achebe" },
      { title: "To the Lighthouse", author: "Virginia Woolf" },
      { title: "Tropic of Cancer", author: "Henry Miller" },
      { title: "Ubik", author: "Philip K. Dick" },
      { title: "Under the Net", author: "Iris Murdoch" },
      { title: "Under the Volcano", author: "Malcolm Lowry" },
      { title: "Watchmen", author: "Alan Moore" },
      { title: "White Teeth", author: "Zadie Smith" },
      { title: "Wide Sargasso Sea", author: "Jean Rhys" },
      { title: "Winesburg, Ohio", author: "Sherwood Anderson" },
      { title: "The Wings of the Dove", author: "Henry James" },
      { title: "Women in Love", author: "D.H. Lawrence" },
      { title: "An American Tragedy", author: "Theodore Dreiser" },
      { title: "Animal Farm", author: "George Orwell" },
      { title: "Are You There God? It's Me, Margaret", author: "Judy Blume" },
      { title: "Brideshead Revisited", author: "Evelyn Waugh" },
      { title: "The Bridge of San Luis Rey", author: "Thornton Wilder" },
      { title: "Call It Sleep", author: "Henry Roth" },
      { title: "A Death in the Family", author: "James Agee" },
      { title: "The Death of the Heart", author: "Elizabeth Bowen" },
      { title: "Deliverance", author: "James Dickey" },
      { title: "Dog Soldiers", author: "Robert Stone" },
      { title: "Falconer", author: "John Cheever" },
      { title: "The French Lieutenant's Woman", author: "John Fowles" },
      { title: "The Golden Notebook", author: "Doris Lessing" },
      { title: "Go Tell It on the Mountain", author: "James Baldwin" },
      { title: "Gone with the Wind", author: "Margaret Mitchell" },
      { title: "Gravity's Rainbow", author: "Thomas Pynchon" },
      { title: "The Grapes of Wrath", author: "John Steinbeck" },
      { title: "The Heart Is a Lonely Hunter", author: "Carson McCullers" },
      { title: "The Heart of the Matter", author: "Graham Greene" },
      { title: "Herzog", author: "Saul Bellow" },
      { title: "Housekeeping", author: "Marilynne Robinson" },
      { title: "I, Claudius", author: "Robert Graves" },
      { title: "Infinite Jest", author: "David Foster Wallace" },
      { title: "The Jungle", author: "Upton Sinclair" },
      { title: "1984", author: "George Orwell" },
      { title: "Brave New World", author: "Aldous Huxley" },
      { title: "Darkness at Noon", author: "Arthur Koestler" },
      { title: "The Day of the Locust", author: "Nathanael West" },
      { title: "Lord of the Flies", author: "William Golding" },
      { title: "Lucky Jim", author: "Kingsley Amis" },
      { title: "The Man Who Loved Children", author: "Christina Stead" },
      { title: "Loving", author: "Henry Green" },
      { title: "Ulysses", author: "James Joyce" },
      { title: "U.S.A. Trilogy", author: "John Dos Passos" },
    ]
  },
  guardian: {
    title: "The Guardian's 100 Best Novels",
    source: "The Guardian",
    year: "2015",
    desc: "Robert McCrum's selection of the finest novels written in English, from Robinson Crusoe to American Pastoral. A journey through 300 years of the English-language novel.",
    books: [
      { title: "The Pilgrim's Progress", author: "John Bunyan" },
      { title: "Robinson Crusoe", author: "Daniel Defoe" },
      { title: "Gulliver's Travels", author: "Jonathan Swift" },
      { title: "Clarissa", author: "Samuel Richardson" },
      { title: "Tom Jones", author: "Henry Fielding" },
      { title: "The Life and Opinions of Tristram Shandy", author: "Laurence Sterne" },
      { title: "Emma", author: "Jane Austen" },
      { title: "Frankenstein", author: "Mary Shelley" },
      { title: "The Narrative of Arthur Gordon Pym", author: "Edgar Allan Poe" },
      { title: "Vanity Fair", author: "William Makepeace Thackeray" },
      { title: "Jane Eyre", author: "Charlotte Brontë" },
      { title: "David Copperfield", author: "Charles Dickens" },
      { title: "Moby-Dick", author: "Herman Melville" },
      { title: "Middlemarch", author: "George Eliot" },
      { title: "The Adventures of Huckleberry Finn", author: "Mark Twain" },
      { title: "The Picture of Dorian Gray", author: "Oscar Wilde" },
      { title: "The Sign of Four", author: "Arthur Conan Doyle" },
      { title: "Jude the Obscure", author: "Thomas Hardy" },
      { title: "The Turn of the Screw", author: "Henry James" },
      { title: "Heart of Darkness", author: "Joseph Conrad" },
      { title: "Wuthering Heights", author: "Emily Brontë" },
      { title: "The Scarlet Letter", author: "Nathaniel Hawthorne" },
      { title: "Alice's Adventures in Wonderland", author: "Lewis Carroll" },
      { title: "Little Women", author: "Louisa May Alcott" },
      { title: "The Way We Live Now", author: "Anthony Trollope" },
      { title: "The Woman in White", author: "Wilkie Collins" },
      { title: "Great Expectations", author: "Charles Dickens" },
      { title: "Silas Marner", author: "George Eliot" },
      { title: "Bleak House", author: "Charles Dickens" },
      { title: "Treasure Island", author: "Robert Louis Stevenson" },
      { title: "Kim", author: "Rudyard Kipling" },
      { title: "The Wonderful Wizard of Oz", author: "L. Frank Baum" },
      { title: "The Hound of the Baskervilles", author: "Arthur Conan Doyle" },
      { title: "The Call of the Wild", author: "Jack London" },
      { title: "The Golden Bowl", author: "Henry James" },
      { title: "The Wind in the Willows", author: "Kenneth Grahame" },
      { title: "The Secret Agent", author: "Joseph Conrad" },
      { title: "A Room with a View", author: "E.M. Forster" },
      { title: "The Secret Garden", author: "Frances Hodgson Burnett" },
      { title: "Sons and Lovers", author: "D.H. Lawrence" },
      { title: "The Good Soldier", author: "Ford Madox Ford" },
      { title: "The Thirty-Nine Steps", author: "John Buchan" },
      { title: "The Age of Innocence", author: "Edith Wharton" },
      { title: "Ulysses", author: "James Joyce" },
      { title: "A Passage to India", author: "E.M. Forster" },
      { title: "The Great Gatsby", author: "F. Scott Fitzgerald" },
      { title: "Mrs Dalloway", author: "Virginia Woolf" },
      { title: "The Sun Also Rises", author: "Ernest Hemingway" },
      { title: "To the Lighthouse", author: "Virginia Woolf" },
      { title: "Orlando", author: "Virginia Woolf" },
      { title: "As I Lay Dying", author: "William Faulkner" },
      { title: "Brave New World", author: "Aldous Huxley" },
      { title: "Cold Comfort Farm", author: "Stella Gibbons" },
      { title: "Scoop", author: "Evelyn Waugh" },
      { title: "The Big Sleep", author: "Raymond Chandler" },
      { title: "Party Going", author: "Henry Green" },
      { title: "At Swim-Two-Birds", author: "Flann O'Brien" },
      { title: "The Grapes of Wrath", author: "John Steinbeck" },
      { title: "Joy in the Morning", author: "P.G. Wodehouse" },
      { title: "All the King's Men", author: "Robert Penn Warren" },
      { title: "Under the Volcano", author: "Malcolm Lowry" },
      { title: "Nineteen Eighty-Four", author: "George Orwell" },
      { title: "The End of the Affair", author: "Graham Greene" },
      { title: "The Catcher in the Rye", author: "J.D. Salinger" },
      { title: "The Adventures of Augie March", author: "Saul Bellow" },
      { title: "Lord of the Flies", author: "William Golding" },
      { title: "Lolita", author: "Vladimir Nabokov" },
      { title: "On the Road", author: "Jack Kerouac" },
      { title: "Voss", author: "Patrick White" },
      { title: "To Kill a Mockingbird", author: "Harper Lee" },
      { title: "The Prime of Miss Jean Brodie", author: "Muriel Spark" },
      { title: "Catch-22", author: "Joseph Heller" },
      { title: "A Clockwork Orange", author: "Anthony Burgess" },
      { title: "A Single Man", author: "Christopher Isherwood" },
      { title: "In Cold Blood", author: "Truman Capote" },
      { title: "The Bell Jar", author: "Sylvia Plath" },
      { title: "Portnoy's Complaint", author: "Philip Roth" },
      { title: "Mrs Palfrey at the Claremont", author: "Elizabeth Taylor" },
      { title: "Rabbit Redux", author: "John Updike" },
      { title: "Song of Solomon", author: "Toni Morrison" },
      { title: "A Bend in the River", author: "V.S. Naipaul" },
      { title: "Midnight's Children", author: "Salman Rushdie" },
      { title: "Housekeeping", author: "Marilynne Robinson" },
      { title: "Money", author: "Martin Amis" },
      { title: "An Artist of the Floating World", author: "Kazuo Ishiguro" },
      { title: "The Beginning of Spring", author: "Penelope Fitzgerald" },
      { title: "Possession", author: "A.S. Byatt" },
      { title: "Amongst Women", author: "John McGahern" },
      { title: "Underworld", author: "Don DeLillo" },
      { title: "Disgrace", author: "J.M. Coetzee" },
      { title: "True History of the Kelly Gang", author: "Peter Carey" },
      { title: "The Corrections", author: "Jonathan Franzen" },
      { title: "Atonement", author: "Ian McEwan" },
      { title: "Fingersmith", author: "Sarah Waters" },
      { title: "The Known World", author: "Edward P. Jones" },
      { title: "Small Island", author: "Andrea Levy" },
      { title: "Never Let Me Go", author: "Kazuo Ishiguro" },
      { title: "The Brief Wondrous Life of Oscar Wao", author: "Junot Díaz" },
      { title: "Wolf Hall", author: "Hilary Mantel" },
      { title: "American Pastoral", author: "Philip Roth" },
    ]
  }
};
