create table if not exists public.arcade_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game text not null check (game in ('bookworm','shelf-breaker','cover-match','guess-the-cover','first-edition')),
  score integer not null check (score >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, game)
);

alter table public.arcade_scores enable row level security;

create policy "Users can read their arcade scores"
  on public.arcade_scores for select
  using (auth.uid() = user_id);

create policy "Users can insert their arcade scores"
  on public.arcade_scores for insert
  with check (auth.uid() = user_id);

create policy "Users can update their arcade scores"
  on public.arcade_scores for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
